### ISSUE TITLE
Issue Tracker: Sync vscode selections

### ISSUE THREAD

**Issue by theol0403** [vscode-neovim/vscode-neovim#1265]
Two way sync, including mouse and selections.

- [x] https://github.com/vscode-neovim/vscode-neovim/issues/172
- [x] https://github.com/vscode-neovim/vscode-neovim/issues/553
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/97
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/1166
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/251
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/370
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/434
- [x] https://github.com/vscode-neovim/vscode-neovim/issues/507
- [x] https://github.com/vscode-neovim/vscode-neovim/issues/1103
- [x] https://github.com/vscode-neovim/vscode-neovim/issues/1219
- [x] https://github.com/vscode-neovim/vscode-neovim/issues/1212
- [ ] https://github.com/vscode-neovim/vscode-neovim/issues/576
