### ISSUE TITLE
bug: Cannot load init.lua using NVIM_APPNAME with WSL

### ISSUE THREAD

**Issue by jackblackevo** [vscode-neovim/vscode-neovim#1295]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Windows 11 (WSL2)

### Describe the bug

When using NVIM_APPNAME, vscode-neovim does not load init.lua via NVIM_APPNAME.

### Steps To Reproduce

1. Delete ~/.config/nvim/init.lua.
2. Set NVIM_APPNAME to `my-app`.
3. Create ~/.config/my-app/init.lua:
   ```lua
   vim.keymap.set('n', '<S-l>', 'gt', { remap = true })
   ```
4. Start VSCode, press <kbd>Shift</kbd> + <kbd>l</kbd>, nothing happens.

### Expected Behavior

Trigger the `gt` keybinding.

**Comment by theol0403** [comment]
How are you setting `NVIM_APPNAME`? It's possible that vscode is not picking that up, and/or env variables are not being sent to neovim subprocess.

**Comment by jackblackevo** [comment]
Hi, I have set the `NVIM_APPNAME` to "my-app" in VSCode > File > Preferences > Settings.

VSCode settings.json
```json
{
  "vscode-neovim.NVIM_APPNAME": "my-app"
}
```

**Comment by theol0403** [comment]
Not sure. See if you can trace what's going on here: https://github.com/vscode-neovim/vscode-neovim/blob/414bf7860e5112ae14558ee1723b96f6c6421b18/src/main_controller.ts#L143

**Comment by jackblackevo** [comment]
I opened the `%USERPROFILE%\.vscode\extensions\asvetliakov.vscode-neovim-0.3.1\dist\extension.js` file.

I added the following code:
```javascript
&&console.log('process.env.NVIM_APPNAME',process.env.NVIM_APPNAME)
```

after the code:
```javascript
e.NVIM_APPNAME&&(process.env.NVIM_APPNAME=e.NVIM_APPNAME)
```

Then, I received the following output:
```text
[Extension Host] process.env.NVIM_APPNAME my-app
```

**Comment by justinmk** [comment]
I haven't looked at the full codepath but just setting `process.env.NVIM_APPNAME` in the node process doesn't seem right. It would be better to explicitly set NVIM_APPNAME wherever we actually spawn the `nvim` process.

**Comment by theol0403** [comment]
@jackblackevo give the PR a try, you can download vsix from actions artifacts

**Comment by jackblackevo** [comment]
Hi, I downloaded and installed vscode-neovim-5b8250706a1e0d4e7201fb620600cf2f7c46694c.vsix (vscode-neovim.zip) from the [#1295 Action Summary](https://github.com/vscode-neovim/vscode-neovim/actions/runs/5490850007), but it is still not working.

**Comment by jackblackevo** [comment]
@theol0403 I have left some comments in the #1303.
