### ISSUE TITLE
Optimize startup error messages

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#2234]
- [x] Notify that `prerelease` differs from `release` #2229.
- [ ] Provide additional troubleshooting steps during remote development.
- [ ] For linux(?) mention `useWsl` and link to our WSL setup docs. https://github.com/vscode-neovim/vscode-neovim/issues/2247
    - [ ] also hint about `extensionKind` ?
- [x] Display all detected invalid Nvim versions when no valid version is found.
    - addressed by the `View Logs` button added in [#2287](https://github.com/vscode-neovim/vscode-neovim/pull/2287)
- [x] mention the exact path in the message, to prevent confusion in [remote scenarios](https://github.com/vscode-neovim/vscode-neovim/issues/2251#issuecomment-2353762071)
    - addressed by the `View Logs` button added in [#2287](https://github.com/vscode-neovim/vscode-neovim/pull/2287)

**Comment by justinmk** [comment]
Do you think it's worth adding optional `paths: string[]` and `dirs: string[]` arguments to `findNvim()` ? Then we could use `findNvim()` to handle all cases, including when the user has set an hardcoded path in their settings.

**Comment by justinmk** [comment]
added WSL item to the todo list.

**Comment by justinmk** [comment]
`findNvim` now has `firstMatch` https://github.com/neovim/node-client/issues/370

**Comment by xiyaowong** [comment]
> Do you think it's worth adding optional `paths: string[]` and `dirs: string[]` arguments to `findNvim()` 

I don't think it's needed. Most of the problems are:  
1. Version is too low.  
2. Wrong location when doing remote development.  
3. Permission issues (rare).

It's enough to search in `env:Path`.

**Comment by justinmk** [comment]
But we have a redundant code path here that shows a different message and duplicates the logic of `findNvim`: https://github.com/vscode-neovim/vscode-neovim/blob/ccd89d3e457ee968c09eb13d711bde0e0097a3f9/runtime/vscode-neovim.vim#L24-L55

If `findNvim` accepted extra paths/dirs, then we could delete the above code.

**Comment by xiyaowong** [comment]
> But we allow users to configure arbitrary locations in vscode settings. `findNvim` doesn't handle that (yet).
> 

If the users set the path themselves, then they should be responsible for it.

> And we have a redundant code path here that shows a different message and duplicates the logic of `findNvim`:
> 
> If `findNvim` accepted extra paths/dirs, then we could delete the above code.

How about

```mermaid
graph TD
    A[Find Neovim] --> B{User specified a path}

	B -->|Yes| C{Does the path exist?}
	B -->|No| D[Search in env:Path]

    C -->|Yes| E[Use the specified path]
	C -->|No| F[Search in the parent directory of the specified path]

    E --> G[Check version in Neovim]
```

**Comment by justinmk** [comment]
> If the users set the path themselves, then they should be responsible for it.

But we already try to handle it and show useful messages in [the code that I linked](https://github.com/vscode-neovim/vscode-neovim/blob/ccd89d3e457ee968c09eb13d711bde0e0097a3f9/runtime/vscode-neovim.vim#L24-L55). And 50% of the recent [startup issues](https://github.com/vscode-neovim/vscode-neovim/issues/2251#issuecomment-2353762071) were from users that had set a path.



> How about

Everything in your diagram would be handled by the recent features added to findNvim:

- https://github.com/neovim/node-client/pull/400

**Comment by xiyaowong** [comment]
Good 👍

**Comment by justinmk** [comment]
released node-client 5.3.0: https://github.com/vscode-neovim/vscode-neovim/pull/2278

**Comment by justinmk** [comment]
> If `findNvim` accepted extra paths/dirs, then we could delete the above code.

Implemented in https://github.com/vscode-neovim/vscode-neovim/pull/2287
